/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ApiPortfolioSkillsRouteImport } from './routes/api.portfolio.skills'
import { Route as ApiPortfolioProjectsRouteImport } from './routes/api.portfolio.projects'
import { Route as ApiPortfolioMessagesRouteImport } from './routes/api.portfolio.messages'
import { Route as ApiPortfolioExperienceRouteImport } from './routes/api.portfolio.experience'
import { Route as ApiPortfolioDataRouteImport } from './routes/api.portfolio.data'
import { Route as ApiPortfolioContactRouteImport } from './routes/api.portfolio.contact'
import { Route as ApiPortfolioCertificatesRouteImport } from './routes/api.portfolio.certificates'
import { Route as ApiPortfolioAboutRouteImport } from './routes/api.portfolio.about'
import { Route as ApiAdminUploadRouteImport } from './routes/api.admin.upload'
import { Route as ApiAdminResumeRouteImport } from './routes/api.admin.resume'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiPortfolioProjectsIdRouteImport } from './routes/api.portfolio.projects.$id'
import { Route as ApiPortfolioMessagesIdRouteImport } from './routes/api.portfolio.messages.$id'
import { Route as ApiPortfolioExperienceIdRouteImport } from './routes/api.portfolio.experience.$id'
import { Route as ApiPortfolioCertificatesIdRouteImport } from './routes/api.portfolio.certificates.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPortfolioSkillsRoute = ApiPortfolioSkillsRouteImport.update({
  id: '/api/portfolio/skills',
  path: '/api/portfolio/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioProjectsRoute = ApiPortfolioProjectsRouteImport.update({
  id: '/api/portfolio/projects',
  path: '/api/portfolio/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioMessagesRoute = ApiPortfolioMessagesRouteImport.update({
  id: '/api/portfolio/messages',
  path: '/api/portfolio/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioExperienceRoute = ApiPortfolioExperienceRouteImport.update({
  id: '/api/portfolio/experience',
  path: '/api/portfolio/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioDataRoute = ApiPortfolioDataRouteImport.update({
  id: '/api/portfolio/data',
  path: '/api/portfolio/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioContactRoute = ApiPortfolioContactRouteImport.update({
  id: '/api/portfolio/contact',
  path: '/api/portfolio/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioCertificatesRoute =
  ApiPortfolioCertificatesRouteImport.update({
    id: '/api/portfolio/certificates',
    path: '/api/portfolio/certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPortfolioAboutRoute = ApiPortfolioAboutRouteImport.update({
  id: '/api/portfolio/about',
  path: '/api/portfolio/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResumeRoute = ApiAdminResumeRouteImport.update({
  id: '/api/admin/resume',
  path: '/api/admin/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioProjectsIdRoute = ApiPortfolioProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPortfolioProjectsRoute,
} as any)
const ApiPortfolioMessagesIdRoute = ApiPortfolioMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPortfolioMessagesRoute,
} as any)
const ApiPortfolioExperienceIdRoute =
  ApiPortfolioExperienceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPortfolioExperienceRoute,
  } as any)
const ApiPortfolioCertificatesIdRoute =
  ApiPortfolioCertificatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPortfolioCertificatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/portfolio/about': typeof ApiPortfolioAboutRoute
  '/api/portfolio/certificates': typeof ApiPortfolioCertificatesRouteWithChildren
  '/api/portfolio/contact': typeof ApiPortfolioContactRoute
  '/api/portfolio/data': typeof ApiPortfolioDataRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRouteWithChildren
  '/api/portfolio/messages': typeof ApiPortfolioMessagesRouteWithChildren
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRouteWithChildren
  '/api/portfolio/skills': typeof ApiPortfolioSkillsRoute
  '/api/portfolio/certificates/$id': typeof ApiPortfolioCertificatesIdRoute
  '/api/portfolio/experience/$id': typeof ApiPortfolioExperienceIdRoute
  '/api/portfolio/messages/$id': typeof ApiPortfolioMessagesIdRoute
  '/api/portfolio/projects/$id': typeof ApiPortfolioProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/portfolio/about': typeof ApiPortfolioAboutRoute
  '/api/portfolio/certificates': typeof ApiPortfolioCertificatesRouteWithChildren
  '/api/portfolio/contact': typeof ApiPortfolioContactRoute
  '/api/portfolio/data': typeof ApiPortfolioDataRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRouteWithChildren
  '/api/portfolio/messages': typeof ApiPortfolioMessagesRouteWithChildren
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRouteWithChildren
  '/api/portfolio/skills': typeof ApiPortfolioSkillsRoute
  '/api/portfolio/certificates/$id': typeof ApiPortfolioCertificatesIdRoute
  '/api/portfolio/experience/$id': typeof ApiPortfolioExperienceIdRoute
  '/api/portfolio/messages/$id': typeof ApiPortfolioMessagesIdRoute
  '/api/portfolio/projects/$id': typeof ApiPortfolioProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/resume': typeof ApiAdminResumeRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/portfolio/about': typeof ApiPortfolioAboutRoute
  '/api/portfolio/certificates': typeof ApiPortfolioCertificatesRouteWithChildren
  '/api/portfolio/contact': typeof ApiPortfolioContactRoute
  '/api/portfolio/data': typeof ApiPortfolioDataRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRouteWithChildren
  '/api/portfolio/messages': typeof ApiPortfolioMessagesRouteWithChildren
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRouteWithChildren
  '/api/portfolio/skills': typeof ApiPortfolioSkillsRoute
  '/api/portfolio/certificates/$id': typeof ApiPortfolioCertificatesIdRoute
  '/api/portfolio/experience/$id': typeof ApiPortfolioExperienceIdRoute
  '/api/portfolio/messages/$id': typeof ApiPortfolioMessagesIdRoute
  '/api/portfolio/projects/$id': typeof ApiPortfolioProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin/'
    | '/api/admin/login'
    | '/api/admin/resume'
    | '/api/admin/upload'
    | '/api/portfolio/about'
    | '/api/portfolio/certificates'
    | '/api/portfolio/contact'
    | '/api/portfolio/data'
    | '/api/portfolio/experience'
    | '/api/portfolio/messages'
    | '/api/portfolio/projects'
    | '/api/portfolio/skills'
    | '/api/portfolio/certificates/$id'
    | '/api/portfolio/experience/$id'
    | '/api/portfolio/messages/$id'
    | '/api/portfolio/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin'
    | '/api/admin/login'
    | '/api/admin/resume'
    | '/api/admin/upload'
    | '/api/portfolio/about'
    | '/api/portfolio/certificates'
    | '/api/portfolio/contact'
    | '/api/portfolio/data'
    | '/api/portfolio/experience'
    | '/api/portfolio/messages'
    | '/api/portfolio/projects'
    | '/api/portfolio/skills'
    | '/api/portfolio/certificates/$id'
    | '/api/portfolio/experience/$id'
    | '/api/portfolio/messages/$id'
    | '/api/portfolio/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin/'
    | '/api/admin/login'
    | '/api/admin/resume'
    | '/api/admin/upload'
    | '/api/portfolio/about'
    | '/api/portfolio/certificates'
    | '/api/portfolio/contact'
    | '/api/portfolio/data'
    | '/api/portfolio/experience'
    | '/api/portfolio/messages'
    | '/api/portfolio/projects'
    | '/api/portfolio/skills'
    | '/api/portfolio/certificates/$id'
    | '/api/portfolio/experience/$id'
    | '/api/portfolio/messages/$id'
    | '/api/portfolio/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminResumeRoute: typeof ApiAdminResumeRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiPortfolioAboutRoute: typeof ApiPortfolioAboutRoute
  ApiPortfolioCertificatesRoute: typeof ApiPortfolioCertificatesRouteWithChildren
  ApiPortfolioContactRoute: typeof ApiPortfolioContactRoute
  ApiPortfolioDataRoute: typeof ApiPortfolioDataRoute
  ApiPortfolioExperienceRoute: typeof ApiPortfolioExperienceRouteWithChildren
  ApiPortfolioMessagesRoute: typeof ApiPortfolioMessagesRouteWithChildren
  ApiPortfolioProjectsRoute: typeof ApiPortfolioProjectsRouteWithChildren
  ApiPortfolioSkillsRoute: typeof ApiPortfolioSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/portfolio/skills': {
      id: '/api/portfolio/skills'
      path: '/api/portfolio/skills'
      fullPath: '/api/portfolio/skills'
      preLoaderRoute: typeof ApiPortfolioSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/projects': {
      id: '/api/portfolio/projects'
      path: '/api/portfolio/projects'
      fullPath: '/api/portfolio/projects'
      preLoaderRoute: typeof ApiPortfolioProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/messages': {
      id: '/api/portfolio/messages'
      path: '/api/portfolio/messages'
      fullPath: '/api/portfolio/messages'
      preLoaderRoute: typeof ApiPortfolioMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/experience': {
      id: '/api/portfolio/experience'
      path: '/api/portfolio/experience'
      fullPath: '/api/portfolio/experience'
      preLoaderRoute: typeof ApiPortfolioExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/data': {
      id: '/api/portfolio/data'
      path: '/api/portfolio/data'
      fullPath: '/api/portfolio/data'
      preLoaderRoute: typeof ApiPortfolioDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/contact': {
      id: '/api/portfolio/contact'
      path: '/api/portfolio/contact'
      fullPath: '/api/portfolio/contact'
      preLoaderRoute: typeof ApiPortfolioContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/certificates': {
      id: '/api/portfolio/certificates'
      path: '/api/portfolio/certificates'
      fullPath: '/api/portfolio/certificates'
      preLoaderRoute: typeof ApiPortfolioCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/about': {
      id: '/api/portfolio/about'
      path: '/api/portfolio/about'
      fullPath: '/api/portfolio/about'
      preLoaderRoute: typeof ApiPortfolioAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resume': {
      id: '/api/admin/resume'
      path: '/api/admin/resume'
      fullPath: '/api/admin/resume'
      preLoaderRoute: typeof ApiAdminResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/projects/$id': {
      id: '/api/portfolio/projects/$id'
      path: '/$id'
      fullPath: '/api/portfolio/projects/$id'
      preLoaderRoute: typeof ApiPortfolioProjectsIdRouteImport
      parentRoute: typeof ApiPortfolioProjectsRoute
    }
    '/api/portfolio/messages/$id': {
      id: '/api/portfolio/messages/$id'
      path: '/$id'
      fullPath: '/api/portfolio/messages/$id'
      preLoaderRoute: typeof ApiPortfolioMessagesIdRouteImport
      parentRoute: typeof ApiPortfolioMessagesRoute
    }
    '/api/portfolio/experience/$id': {
      id: '/api/portfolio/experience/$id'
      path: '/$id'
      fullPath: '/api/portfolio/experience/$id'
      preLoaderRoute: typeof ApiPortfolioExperienceIdRouteImport
      parentRoute: typeof ApiPortfolioExperienceRoute
    }
    '/api/portfolio/certificates/$id': {
      id: '/api/portfolio/certificates/$id'
      path: '/$id'
      fullPath: '/api/portfolio/certificates/$id'
      preLoaderRoute: typeof ApiPortfolioCertificatesIdRouteImport
      parentRoute: typeof ApiPortfolioCertificatesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPortfolioCertificatesRouteChildren {
  ApiPortfolioCertificatesIdRoute: typeof ApiPortfolioCertificatesIdRoute
}

const ApiPortfolioCertificatesRouteChildren: ApiPortfolioCertificatesRouteChildren =
  {
    ApiPortfolioCertificatesIdRoute: ApiPortfolioCertificatesIdRoute,
  }

const ApiPortfolioCertificatesRouteWithChildren =
  ApiPortfolioCertificatesRoute._addFileChildren(
    ApiPortfolioCertificatesRouteChildren,
  )

interface ApiPortfolioExperienceRouteChildren {
  ApiPortfolioExperienceIdRoute: typeof ApiPortfolioExperienceIdRoute
}

const ApiPortfolioExperienceRouteChildren: ApiPortfolioExperienceRouteChildren =
  {
    ApiPortfolioExperienceIdRoute: ApiPortfolioExperienceIdRoute,
  }

const ApiPortfolioExperienceRouteWithChildren =
  ApiPortfolioExperienceRoute._addFileChildren(
    ApiPortfolioExperienceRouteChildren,
  )

interface ApiPortfolioMessagesRouteChildren {
  ApiPortfolioMessagesIdRoute: typeof ApiPortfolioMessagesIdRoute
}

const ApiPortfolioMessagesRouteChildren: ApiPortfolioMessagesRouteChildren = {
  ApiPortfolioMessagesIdRoute: ApiPortfolioMessagesIdRoute,
}

const ApiPortfolioMessagesRouteWithChildren =
  ApiPortfolioMessagesRoute._addFileChildren(ApiPortfolioMessagesRouteChildren)

interface ApiPortfolioProjectsRouteChildren {
  ApiPortfolioProjectsIdRoute: typeof ApiPortfolioProjectsIdRoute
}

const ApiPortfolioProjectsRouteChildren: ApiPortfolioProjectsRouteChildren = {
  ApiPortfolioProjectsIdRoute: ApiPortfolioProjectsIdRoute,
}

const ApiPortfolioProjectsRouteWithChildren =
  ApiPortfolioProjectsRoute._addFileChildren(ApiPortfolioProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminResumeRoute: ApiAdminResumeRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiPortfolioAboutRoute: ApiPortfolioAboutRoute,
  ApiPortfolioCertificatesRoute: ApiPortfolioCertificatesRouteWithChildren,
  ApiPortfolioContactRoute: ApiPortfolioContactRoute,
  ApiPortfolioDataRoute: ApiPortfolioDataRoute,
  ApiPortfolioExperienceRoute: ApiPortfolioExperienceRouteWithChildren,
  ApiPortfolioMessagesRoute: ApiPortfolioMessagesRouteWithChildren,
  ApiPortfolioProjectsRoute: ApiPortfolioProjectsRouteWithChildren,
  ApiPortfolioSkillsRoute: ApiPortfolioSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
